const ORDER_LINKS={
  takeaway:'https://www.takeaway.com/be/menu/goodfellas-vilvoorde-vilvoorde',
  ubereats:'https://www.ubereats.com/be/store/goodfellas-vilvoorde/KhaZmnmpX9CYa98NBAnrwQ',
  deliveroo:'https://deliveroo.be/en/menu/brussels/vilvoorde-center/goodfellas-vilvoorde'
};
const t={
fr:{skip:'Aller au contenu',navHome:'Accueil',navMenu:'Nos spécialités',navGallery:'Galerie',navOrder:'Commander',navAbout:'À propos',navContact:'Contact',order:'Commander',heroTitle:'Le goût de <em>New York</em><br>au cœur de Vilvorde',heroText:'Pizzas, burgers, tacos et recettes généreuses préparés pour les vrais gourmands.',viewMenu:'Voir le menu',callNow:'Appeler maintenant',halal:'Viandes halal',certificate:'Certificat à faire valider par le restaurant',pickupDelivery:'À emporter · Livraison',delivery:'Livraison',specialtiesTitle:'Nos <em>spécialités</em>',catPizza:'Pizzas',catBurger:'Burgers',catTacos:'Tacos & wraps',catChicken:'Chicken',catDrinks:'Boissons & desserts',discover:'Découvrir la carte →',orderTitle:'Sur place, à emporter<br><em>ou livré chez vous.</em>',orderText:'Retrouvez les prix et la disponibilité en temps réel sur votre plateforme préférée.',orderPickup:'Commander à emporter ou en livraison',orderDelivery:'Commander en livraison',aboutTitle:'Bienvenue chez<br><em>Goodfellas</em>',aboutText:'Une cuisine généreuse qui mêle pizzas italiennes et street food dans une ambiance moderne et conviviale. Découvrez la carte complète et les disponibilités sur nos plateformes de commande.',contactTitle:'Contact & <em>accès</em>',address:'ADRESSE',phone:'TÉLÉPHONE',hours:'HORAIRES',emailPending:'Adresse e-mail à confirmer par le restaurant',hoursText:'Consultez la plateforme de commande pour les horaires actuels.',call:'Appeler le restaurant',mapPrivacy:'La carte Google Maps ne sera chargée qu’après votre accord.',showMap:'Afficher la carte',privacy:'Confidentialité · Belgique',mockup:'Maquette non officielle',certTitle:'Information halal',certText:'Le certificat officiel n’a pas encore été fourni pour cette maquette. Il devra être ajouté ici uniquement après validation par le restaurant.'},
nl:{skip:'Ga naar inhoud',navHome:'Home',navMenu:'Onze specialiteiten',navGallery:'Galerij',navOrder:'Bestellen',navAbout:'Over ons',navContact:'Contact',order:'Bestellen',heroTitle:'De smaak van <em>New York</em><br>in hartje Vilvoorde',heroText:'Pizza’s, burgers, taco’s en royale gerechten voor echte lekkerbekken.',viewMenu:'Bekijk het menu',callNow:'Bel nu',halal:'Halal vlees',certificate:'Certificaat moet door het restaurant worden bevestigd',pickupDelivery:'Afhalen · Levering',delivery:'Levering',specialtiesTitle:'Onze <em>specialiteiten</em>',catPizza:'Pizza’s',catBurger:'Burgers',catTacos:'Taco’s & wraps',catChicken:'Chicken',catDrinks:'Dranken & desserts',discover:'Ontdek de kaart →',orderTitle:'Ter plaatse, afhalen<br><em>of thuisbezorgd.</em>',orderText:'Bekijk actuele prijzen en beschikbaarheid op uw favoriete platform.',orderPickup:'Bestel voor afhaling of levering',orderDelivery:'Bestel voor levering',aboutTitle:'Welkom bij<br><em>Goodfellas</em>',aboutText:'Een royale keuken die Italiaanse pizza’s en streetfood combineert in een moderne, gezellige sfeer. Ontdek de volledige kaart en beschikbaarheid op onze bestelplatforms.',contactTitle:'Contact & <em>route</em>',address:'ADRES',phone:'TELEFOON',hours:'OPENINGSUREN',emailPending:'E-mailadres nog te bevestigen door het restaurant',hoursText:'Bekijk het bestelplatform voor de actuele openingsuren.',call:'Bel het restaurant',mapPrivacy:'Google Maps wordt pas geladen nadat u toestemming geeft.',showMap:'Kaart tonen',privacy:'Privacy · België',mockup:'Niet-officieel ontwerp',certTitle:'Halal-informatie',certText:'Het officiële certificaat is nog niet verstrekt voor dit ontwerp. Voeg het hier pas toe na bevestiging door het restaurant.'}}
let lang='fr';
document.querySelectorAll('[data-service]').forEach(a=>a.href=ORDER_LINKS[a.dataset.service]);
document.querySelector('.lang')?.addEventListener('click',()=>{lang=lang==='fr'?'nl':'fr';document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{if(t[lang][el.dataset.i18n])el.innerHTML=t[lang][el.dataset.i18n]});document.querySelector('.lang').innerHTML=lang==='fr'?'<strong>FR</strong><span>/</span> NL':'FR <span>/</span> <strong>NL</strong>'});
const menuBtn=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-links');menuBtn?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});nav?.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));
const topBtn=document.querySelector('.back-top');addEventListener('scroll',()=>{document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>35);topBtn?.classList.toggle('show',scrollY>600)});topBtn?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const box=document.querySelector('#map-box'),loadMap=document.querySelector('#load-map');loadMap?.addEventListener('click',()=>{box.innerHTML='<iframe title="Carte Google Maps de Goodfellas Vilvoorde" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Jean+Baptiste+Nowelei+37+1800+Vilvoorde&output=embed"></iframe>'});
const lightbox=document.querySelector('.lightbox');document.querySelector('#gallery')?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;lightbox.querySelector('img').src=b.querySelector('img').src;lightbox.querySelector('p').textContent=b.dataset.caption;lightbox.showModal()});lightbox?.querySelector('button')?.addEventListener('click',()=>lightbox.close());lightbox?.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
const hero=document.querySelector('.hero'),heroSlider=document.querySelector('.hero-slider'),heroSlides=[...document.querySelectorAll('.hero-slide')],heroDots=[...document.querySelectorAll('.hero-dots button')];
let heroIndex=0,heroTimer,swipeStart=null;
const showHeroSlide=(next,restart=true)=>{
  if(!heroSlider||!heroSlides.length)return;
  heroIndex=(next+heroSlides.length)%heroSlides.length;
  heroSlider.style.transform=`translate3d(-${heroIndex*100}%,0,0)`;
  heroSlides.forEach((slide,i)=>{const active=i===heroIndex;slide.classList.toggle('is-active',active);slide.setAttribute('aria-hidden',String(!active))});
  heroDots.forEach((dot,i)=>{const active=i===heroIndex;dot.classList.toggle('is-active',active);active?dot.setAttribute('aria-current','true'):dot.removeAttribute('aria-current')});
  if(restart)startHeroTimer();
};
const startHeroTimer=()=>{clearTimeout(heroTimer);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)heroTimer=setTimeout(()=>showHeroSlide(heroIndex+1),6000)};
document.querySelector('.hero-prev')?.addEventListener('click',()=>showHeroSlide(heroIndex-1));
document.querySelector('.hero-next')?.addEventListener('click',()=>showHeroSlide(heroIndex+1));
heroDots.forEach((dot,i)=>dot.addEventListener('click',()=>showHeroSlide(i)));
hero?.addEventListener('pointerdown',e=>{if(e.target.closest('a,button'))return;swipeStart=e.clientX});
hero?.addEventListener('pointerup',e=>{if(swipeStart===null)return;const distance=e.clientX-swipeStart;swipeStart=null;if(Math.abs(distance)>50)showHeroSlide(heroIndex+(distance<0?1:-1))});
hero?.addEventListener('pointercancel',()=>{swipeStart=null});
document.addEventListener('visibilitychange',()=>document.hidden?clearTimeout(heroTimer):startHeroTimer());
showHeroSlide(0);
document.querySelector('#year').textContent=new Date().getFullYear();
