const ORDER_LINKS={
  takeaway:'https://www.takeaway.com/be/menu/goodfellas-vilvoorde-vilvoorde',
  ubereats:'https://www.ubereats.com/be/store/goodfellas-vilvoorde/KhaZmnmpX9CYa98NBAnrwQ',
  deliveroo:'https://deliveroo.be/en/menu/brussels/vilvoorde-center/goodfellas-vilvoorde'
};
const t={
fr:{skip:'Aller au contenu',navHome:'Accueil',navMenu:'Nos spécialités',navGallery:'Galerie',navOrder:'Commander',navAbout:'À propos',navContact:'Contact',contactUs:'Nous contacter',heroTitle:'Le fast-food<br>version <em>New York</em>',heroText:'Pizzas, burgers, tacos et recettes généreuses préparés pour les vrais gourmands.',viewMenu:'Voir le menu',callNow:'Appeler maintenant',specialtiesTitle:'Nos <em>spécialités</em>',catPizza:'Pizzas',catBurger:'Burgers',catTacos:'Tacos & wraps',catChicken:'Chicken',catDrinks:'Boissons & desserts',discover:'Découvrir la carte →',aboutTitle:'Bienvenue chez<br><em>Goodfellas</em>',aboutText:'Une cuisine généreuse qui mêle pizzas italiennes et street food dans une ambiance moderne et conviviale. Découvrez la carte complète et les disponibilités sur nos plateformes de commande.',contactTitle:'Contact & <em>accès</em>',address:'ADRESSE',phone:'TÉLÉPHONE',hours:'HORAIRES',call:'Appeler le restaurant',privacy:'Confidentialité · Belgique',mockup:'Maquette non officielle'},
nl:{skip:'Ga naar inhoud',navHome:'Home',navMenu:'Onze specialiteiten',navGallery:'Galerij',navOrder:'Bestellen',navAbout:'Over ons',navContact:'Contact',contactUs:'Contacteer ons',heroTitle:'Fastfood<br>in <em>New York-stijl</em>',heroText:'Pizza’s, burgers, taco’s en royale gerechten voor echte lekkerbekken.',viewMenu:'Bekijk het menu',callNow:'Bel nu',specialtiesTitle:'Onze <em>specialiteiten</em>',catPizza:'Pizza’s',catBurger:'Burgers',catTacos:'Taco’s & wraps',catChicken:'Chicken',catDrinks:'Dranken & desserts',discover:'Ontdek de kaart →',aboutTitle:'Welkom bij<br><em>Goodfellas</em>',aboutText:'Een royale keuken die Italiaanse pizza’s en streetfood combineert in een moderne, gezellige sfeer. Ontdek de volledige kaart en beschikbaarheid op onze bestelplatforms.',contactTitle:'Contact & <em>route</em>',address:'ADRES',phone:'TELEFOON',hours:'OPENINGSUREN',call:'Bel het restaurant',privacy:'Privacy · België',mockup:'Niet-officieel ontwerp'}}
let lang='fr';
document.querySelectorAll('[data-service]').forEach(a=>a.href=ORDER_LINKS[a.dataset.service]);
document.querySelector('.lang')?.addEventListener('click',()=>{lang=lang==='fr'?'nl':'fr';document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{if(t[lang][el.dataset.i18n])el.innerHTML=t[lang][el.dataset.i18n]});document.querySelector('.lang').innerHTML=lang==='fr'?'<strong>FR</strong><span>/</span> NL':'FR <span>/</span> <strong>NL</strong>'});
const menuBtn=document.querySelector('.menu-toggle'),nav=document.querySelector('.nav-links');menuBtn?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});nav?.addEventListener('click',()=>{nav.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));
const topBtn=document.querySelector('.back-top');addEventListener('scroll',()=>{document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>35);topBtn?.classList.toggle('show',scrollY>600)});topBtn?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const box=document.querySelector('#map-box'),loadMap=document.querySelector('#load-map');loadMap?.addEventListener('click',()=>{box.innerHTML='<iframe title="Carte Google Maps de Goodfellas Vilvoorde" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q=Jean+Baptiste+Nowelei+37+1800+Vilvoorde&output=embed"></iframe>'});
const lightbox=document.querySelector('.lightbox');document.querySelector('#gallery')?.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;lightbox.querySelector('img').src=b.querySelector('img').src;lightbox.querySelector('p').textContent=b.dataset.caption;lightbox.showModal()});lightbox?.querySelector('button')?.addEventListener('click',()=>lightbox.close());lightbox?.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
const dayIndex=(new Date().getDay()+6)%7;
const todayRow=document.querySelector(`[data-day="${dayIndex}"]`);
if(todayRow){todayRow.classList.add('today');const todayHours=document.querySelector('#today-hours');if(todayHours)todayHours.textContent=`Aujourd’hui · ${todayRow.querySelector('strong').textContent}`}
document.querySelector('#year').textContent=new Date().getFullYear();
