// Modifiez uniquement ces URL pour connecter les vraies plateformes de commande.
const ORDER_LINKS = {
  takeaway: 'https://www.takeaway.com/be-fr/',
  ubereats: 'https://www.ubereats.com/be',
  deliveroo: 'https://deliveroo.be/fr/'
};

const translations = {
  fr:{skip:'Aller au contenu',navHome:'Accueil',navMenu:'Notre menu',navAbout:'À propos',navGallery:'Galerie',navInfo:'Informations',navContact:'Contact',order:'Commander',heroEyebrow:'AMERICAN PIZZERIA & GRILL · VILVOORDE',heroTitle:'Le goût de <em>New York</em><br>au cœur de Vilvorde',heroText:'Pizzas, burgers, tacos et spécialités américaines préparés pour les vrais gourmands.',viewMenu:'Voir le menu',orderNow:'Commander maintenant',halal:'Viandes halal',ourKitchen:'NOTRE CUISINE',specialtiesTitle:'Nos <em>spécialités</em>',specialtiesIntro:'Des recettes généreuses, des ingrédients savoureux et l’esprit des diners new-yorkais.',bestsellers:'LES INCONTOURNABLES',popularTitle:'Plats <em>populaires</em>',popularIntro:'Une sélection de nos recettes les plus gourmandes.',priceNote:'* Les prix et la disponibilité peuvent changer. Consultez la plateforme de commande pour les informations actuelles.',ourStory:'NOTRE HISTOIRE',aboutTitle:'Bienvenue chez<br><em>Goodfellas Vilvoorde</em>',aboutText:'Découvrez une cuisine généreuse mêlant pizzas italiennes et street food américaine dans une ambiance moderne et conviviale. Venez manger sur place, emporter votre commande ou profiter de la livraison.',eatIn:'◆ Sur place',takeAway:'◆ À emporter',delivery:'◆ Livraison',inPictures:'EN IMAGES',galleryTitle:'La galerie <em>Goodfellas</em>',galleryIntro:'Un avant-goût de ce qui vous attend.',findUs:'NOUS TROUVER',infoTitle:'Passez nous <em>voir</em>',address:'ADRESSE',phone:'TÉLÉPHONE',hours:'HORAIRES',hoursText:'Consultez nos réseaux sociaux ou notre plateforme de commande pour les horaires actuels.',call:'Appeler',directions:'Itinéraire',openMaps:'Ouvrir dans Google Maps ↗',hungry:'UNE PETITE FAIM ?',orderTitle:'Commandez vos favoris,<br><em>on s’occupe du reste.</em>',orderText:'Choisissez votre plateforme de commande préférée.',contactKicker:'CONTACT',contactTitle:'Une question ?<br><em>Écrivez-nous.</em>',contactText:'Nous vous répondrons dans les meilleurs délais.',name:'Prénom et nom',email:'Adresse e-mail',tel:'Numéro de téléphone',subject:'Sujet',message:'Message',send:'Envoyer le message',quickLinks:'Navigation',follow:'Suivez-nous',mockup:'Maquette non officielle — en attente de validation',formSuccess:'Merci ! Votre message a bien été préparé. Cette maquette nécessite encore un service backend pour l’envoyer réellement.',formError:'Veuillez compléter correctement les champs obligatoires.'},
  nl:{skip:'Ga naar inhoud',navHome:'Home',navMenu:'Ons menu',navAbout:'Over ons',navGallery:'Galerij',navInfo:'Informatie',navContact:'Contact',order:'Bestellen',heroEyebrow:'AMERICAN PIZZERIA & GRILL · VILVOORDE',heroTitle:'De smaak van <em>New York</em><br>in hartje Vilvoorde',heroText:'Pizza’s, burgers, taco’s en Amerikaanse specialiteiten voor echte lekkerbekken.',viewMenu:'Bekijk het menu',orderNow:'Bestel nu',halal:'Halal vlees',ourKitchen:'ONZE KEUKEN',specialtiesTitle:'Onze <em>specialiteiten</em>',specialtiesIntro:'Royale recepten, smaakvolle ingrediënten en de sfeer van New Yorkse diners.',bestsellers:'DE FAVORIETEN',popularTitle:'Populaire <em>gerechten</em>',popularIntro:'Een selectie van onze lekkerste recepten.',priceNote:'* Prijzen en beschikbaarheid kunnen wijzigen. Raadpleeg het bestelplatform voor actuele informatie.',ourStory:'ONS VERHAAL',aboutTitle:'Welkom bij<br><em>Goodfellas Vilvoorde</em>',aboutText:'Ontdek een royale keuken waarin Italiaanse pizza’s en Amerikaanse streetfood samenkomen in een moderne, gezellige sfeer. Eet bij ons, haal af of laat thuisbezorgen.',eatIn:'◆ Ter plaatse',takeAway:'◆ Afhalen',delivery:'◆ Levering',inPictures:'IN BEELD',galleryTitle:'De <em>Goodfellas</em>-galerij',galleryIntro:'Een voorsmaakje van wat u te wachten staat.',findUs:'VIND ONS',infoTitle:'Kom eens <em>langs</em>',address:'ADRES',phone:'TELEFOON',hours:'OPENINGSUREN',hoursText:'Bekijk onze sociale media of ons bestelplatform voor de actuele openingsuren.',call:'Bellen',directions:'Route',openMaps:'Openen in Google Maps ↗',hungry:'ZIN IN IETS LEKKERS?',orderTitle:'Bestel uw favorieten,<br><em>wij doen de rest.</em>',orderText:'Kies uw favoriete bestelplatform.',contactKicker:'CONTACT',contactTitle:'Een vraag?<br><em>Schrijf ons.</em>',contactText:'We antwoorden zo snel mogelijk.',name:'Voor- en achternaam',email:'E-mailadres',tel:'Telefoonnummer',subject:'Onderwerp',message:'Bericht',send:'Bericht verzenden',quickLinks:'Navigatie',follow:'Volg ons',mockup:'Niet-officieel ontwerp — wacht op goedkeuring',formSuccess:'Bedankt! Uw bericht is voorbereid. Deze demo heeft nog een backend nodig om het echt te verzenden.',formError:'Vul alle verplichte velden correct in.'}
};

const specialties = [
  ['Pizzas New York Style','New York Style Pizza’s','Pizzas généreuses avec une pâte savoureuse et des garnitures variées.','Royale pizza’s met smaakvol deeg en gevarieerd beleg.'],
  ['Pizzas siciliennes','Siciliaanse pizza’s','Pizzas épaisses et gourmandes inspirées de la tradition sicilienne.','Dikke, rijke pizza’s geïnspireerd op de Siciliaanse traditie.'],
  ['Burgers','Burgers','Burgers au bœuf ou au poulet avec différentes sauces et garnitures.','Rund- of kipburgers met diverse sauzen en toppings.'],
  ['Tacos et wraps','Taco’s en wraps','Tacos généreux avec frites, fromage, poulet ou viande.','Royale taco’s met friet, kaas, kip of vlees.'],
  ['Chicken wings','Chicken wings','Ailes de poulet classiques, barbecue ou buffalo.','Kippenvleugels: klassiek, barbecue of buffalo.'],
  ['Milkshakes et boissons','Milkshakes en drankjes','Milkshakes, cafés glacés, limonades et boissons fraîches.','Milkshakes, ijskoffie, limonade en frisse drankjes.']
];
const popular = [
 ['BBQ Chicken Pizza','Poulet grillé, sauce BBQ fumée et oignons rouges.','Gegrilde kip, rokerige BBQ-saus en rode ui.','€ 14,90'],['Pizza Peperoni Beef','Peperoni de bœuf, mozzarella et sauce tomate.','Runderpeperoni, mozzarella en tomatensaus.','€ 13,90'],['Goodfellas Royal Burger','Double bœuf, cheddar, crudités et sauce maison.','Dubbel rundvlees, cheddar, groenten en huissaus.','€ 15,50'],['Brooklyn Chicken Burger','Poulet croustillant, salade et sauce légèrement relevée.','Krokante kip, sla en licht pittige saus.','€ 13,50'],['Taco Yankee','Poulet, frites, fromage et sauce au choix.','Kip, friet, kaas en saus naar keuze.','€ 10,90'],['Taco Gambino','Viande, frites, fromage et légumes grillés.','Vlees, friet, kaas en gegrilde groenten.','€ 11,90'],['Chicken Tenders','Filets de poulet croustillants et sauce maison.','Krokante kipfilets met huissaus.','€ 9,50'],['Chicken Wings','Ailes de poulet BBQ ou buffalo.','Kippenvleugels met BBQ- of buffalosaus.','€ 8,90']
];
const image='images/food-selection.png';
function renderCards(lang='fr'){
  document.querySelector('#special-grid').innerHTML=specialties.map((x,i)=>`<article class="special-card reveal"><img src="${image}" alt="${lang==='fr'?x[0]:x[1]}" loading="lazy"><div class="card-copy"><h3>${lang==='fr'?x[0]:x[1]}</h3><p>${lang==='fr'?x[2]:x[3]}</p></div></article>`).join('');
  document.querySelector('#popular-grid').innerHTML=popular.map((x,i)=>`<article class="food-card reveal"><div class="food-img"><img src="${i<4?image:'images/hero-feast.png'}" alt="${x[0]}" loading="lazy"></div><div class="food-body"><h3>${x[0]}</h3><p>${lang==='fr'?x[1]:x[2]}</p><span class="price">${x[3]}</span></div></article>`).join('');
  observeReveals();
}
document.querySelector('#gallery-grid').innerHTML=Array.from({length:8},(_,i)=>`<button class="gallery-item reveal" data-caption="Goodfellas — ${i+1}"><img src="${i<6?image:'images/hero-feast.png'}" alt="Sélection culinaire Goodfellas ${i+1}" loading="lazy"></button>`).join('');
document.querySelectorAll('.order-link').forEach(a=>a.href=ORDER_LINKS[a.dataset.service]);
let currentLang='fr';
document.querySelector('.lang').addEventListener('click',()=>{currentLang=currentLang==='fr'?'nl':'fr';document.documentElement.lang=currentLang;document.querySelectorAll('[data-i18n]').forEach(el=>{const val=translations[currentLang][el.dataset.i18n];if(val)el.innerHTML=val});document.querySelector('.lang').innerHTML=currentLang==='fr'?'<strong>FR</strong><span>/</span> NL':'FR <span>/</span> <strong>NL</strong>';renderCards(currentLang)});
const menuBtn=document.querySelector('.menu-toggle'),navLinks=document.querySelector('.nav-links');menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)});navLinks.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')});
let observer;function observeReveals(){if(!observer)observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal:not(.visible)').forEach(el=>observer.observe(el))}renderCards();observeReveals();
const back=document.querySelector('.back-top');window.addEventListener('scroll',()=>{document.querySelector('.site-header').classList.toggle('scrolled',scrollY>40);back.classList.toggle('show',scrollY>600)});back.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
const lightbox=document.querySelector('.lightbox');document.querySelector('#gallery-grid').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;lightbox.querySelector('img').src=btn.querySelector('img').src;lightbox.querySelector('p').textContent=btn.dataset.caption;lightbox.showModal()});lightbox.querySelector('button').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target===lightbox)lightbox.close()});
// Démonstration front-end uniquement : branchez ici un backend (Formspree, API, etc.) pour recevoir les messages.
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget,status=form.querySelector('.form-status');form.querySelectorAll('input,textarea').forEach(f=>f.classList.toggle('invalid',!f.checkValidity()));if(!form.checkValidity()){status.textContent=translations[currentLang].formError;status.className='form-status';return}status.textContent=translations[currentLang].formSuccess;status.className='form-status success';form.reset()});
document.querySelector('#year').textContent=new Date().getFullYear();
